# Generated by Django 5.2.14 on 2026-06-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('report_ready', 'Report ready'), ('report_failed', 'Report failed'), ('invite_member', 'Invite member'), ('billing_event', 'Billing event'), ('system_alert', 'System alert')], max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'event', 'channel'], name='notificatio_organiz_69d69c_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_712c2e_idx'), models.Index(fields=['recipient'], name='notificatio_recipie_63a4fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('report_ready', 'Report ready'), ('report_failed', 'Report failed'), ('invite_member', 'Invite member'), ('billing_event', 'Billing event'), ('system_alert', 'System alert')], max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app'), ('webhook', 'Webhook')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'event', 'channel', 'user_id'],
                'indexes': [models.Index(fields=['organization', 'event', 'channel'], name='notificatio_organiz_8b8cff_idx'), models.Index(fields=['user', 'event'], name='notificatio_user_id_5c9ac2_idx')],
            },
        ),
    ]
