# Generated by Django 5.2.14 on 2026-06-10 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('report_ready', 'Report ready'), ('report_failed', 'Report failed'), ('invite_member', 'Invite member'), ('billing_event', 'Billing event'), ('system_alert', 'System alert')], max_length=40)),
                ('title', models.CharField(max_length=240)),
                ('message', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'user', 'is_read'], name='notificatio_organiz_1c7d9d_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_d4dc14_idx')],
            },
        ),
    ]
