# Generated by Django 5.2.14 on 2026-06-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
        ('reports', '0002_seed_default_report_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleInsightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('planned', 'Planned'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('ai_execution_plan', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_insight_requests', to=settings.AUTH_USER_MODEL)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_insight_requests', to='jobs.jobrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_insight_requests', to='organizations.organization')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_insight_requests', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='example_ins_organiz_95cf2c_idx'), models.Index(fields=['created_at'], name='example_ins_created_0ecc7c_idx')],
            },
        ),
    ]
