# Generated by Django 5.2.14 on 2026-06-03 11:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('default_model', models.CharField(blank=True, max_length=120)),
                ('supported_features', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='ai_aiprovid_slug_97b0d8_idx'), models.Index(fields=['is_active', 'status'], name='ai_aiprovid_is_acti_db1523_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField()),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', '-version'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='ai_promptte_key_63cbd5_idx'), models.Index(fields=['version'], name='ai_promptte_version_e852ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_prompt_template_version')],
            },
        ),
        migrations.CreateModel(
            name='AIResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_result_cache', to='organizations.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_cache', to='ai.aiprovider')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_cache', to='ai.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['request_hash'], name='ai_airesult_request_4f4c45_idx'), models.Index(fields=['expires_at'], name='ai_airesult_expires_064a15_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'model', 'request_hash'), name='unique_ai_cache_entry')],
            },
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cached', 'Cached')], default='pending', max_length=20)),
                ('related_entity_type', models.CharField(blank=True, max_length=120)),
                ('related_entity_id', models.CharField(blank=True, max_length=120)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_call_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='ai.aiprovider')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='ai.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ai_aicalllo_organiz_084531_idx'), models.Index(fields=['provider', 'model'], name='ai_aicalllo_provide_1f456a_idx'), models.Index(fields=['status'], name='ai_aicalllo_status_3c78aa_idx')],
            },
        ),
    ]
