# Generated by Django 5.2.14 on 2026-06-03 11:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_default_ai_providers'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('product_area', models.CharField(blank=True, max_length=120)),
                ('default_strategy', models.CharField(choices=[('deterministic', 'Deterministic code/rules'), ('classic_ml', 'Classic ML/DL library'), ('local_model', 'Local small model'), ('low_cost_llm', 'Low-cost LLM'), ('standard_llm', 'Standard LLM'), ('advanced_llm', 'Advanced LLM'), ('human_review', 'Human review')], default='low_cost_llm', max_length=30)),
                ('allowed_strategies', models.JSONField(blank=True, default=list)),
                ('expected_runs_per_month', models.PositiveIntegerField(default=0)),
                ('max_cost_per_run', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_target_ms', models.PositiveIntegerField(default=0)),
                ('quality_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=4)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('requires_structured_output', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='ai_aitaskpr_key_a2a4c0_idx'), models.Index(fields=['product_area'], name='ai_aitaskpr_product_946f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('strategy', models.CharField(choices=[('deterministic', 'Deterministic code/rules'), ('classic_ml', 'Classic ML/DL library'), ('local_model', 'Local small model'), ('low_cost_llm', 'Low-cost LLM'), ('standard_llm', 'Standard LLM'), ('advanced_llm', 'Advanced LLM'), ('human_review', 'Human review')], max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('plan_slug', models.SlugField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('max_cost_per_run', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('max_latency_ms', models.PositiveIntegerField(default=0)),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=4)),
                ('fallback_strategy', models.CharField(blank=True, choices=[('deterministic', 'Deterministic code/rules'), ('classic_ml', 'Classic ML/DL library'), ('local_model', 'Local small model'), ('low_cost_llm', 'Low-cost LLM'), ('standard_llm', 'Standard LLM'), ('advanced_llm', 'Advanced LLM'), ('human_review', 'Human review')], max_length=30)),
                ('fallback_model_name', models.CharField(blank=True, max_length=120)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_model_policies', to='ai.aiprovider')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_policies', to='ai.aiprovider')),
                ('task_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='ai.aitaskprofile')),
            ],
            options={
                'ordering': ['task_profile', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIModelDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.SlugField()),
                ('selected_strategy', models.CharField(choices=[('deterministic', 'Deterministic code/rules'), ('classic_ml', 'Classic ML/DL library'), ('local_model', 'Local small model'), ('low_cost_llm', 'Low-cost LLM'), ('standard_llm', 'Standard LLM'), ('advanced_llm', 'Advanced LLM'), ('human_review', 'Human review')], max_length=30)),
                ('selected_model', models.CharField(blank=True, max_length=120)),
                ('fallback_strategy', models.CharField(blank=True, choices=[('deterministic', 'Deterministic code/rules'), ('classic_ml', 'Classic ML/DL library'), ('local_model', 'Local small model'), ('low_cost_llm', 'Low-cost LLM'), ('standard_llm', 'Standard LLM'), ('advanced_llm', 'Advanced LLM'), ('human_review', 'Human review')], max_length=30)),
                ('fallback_model', models.CharField(blank=True, max_length=120)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('decision_reason', models.TextField(blank=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fallback_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_decision_logs', to='ai.aiprovider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_decisions', to='organizations.organization')),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='ai.aiprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_decisions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='ai.aimodelpolicy')),
                ('task_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='ai.aitaskprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='aimodelpolicy',
            index=models.Index(fields=['task_profile', 'strategy', 'is_active'], name='ai_aimodelp_task_pr_18f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelpolicy',
            index=models.Index(fields=['plan_slug'], name='ai_aimodelp_plan_sl_4bfc00_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelpolicy',
            index=models.Index(fields=['priority'], name='ai_aimodelp_priorit_c280bd_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodeldecisionlog',
            index=models.Index(fields=['organization', 'created_at'], name='ai_aimodeld_organiz_3c3c29_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodeldecisionlog',
            index=models.Index(fields=['task_key', 'selected_strategy'], name='ai_aimodeld_task_ke_6cba29_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodeldecisionlog',
            index=models.Index(fields=['requires_human_review'], name='ai_aimodeld_require_32b214_idx'),
        ),
    ]
