# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_seed_report_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["event_id"], name="billing_str_event_i_dd223a_idx"),
                    models.Index(
                        fields=["event_type", "status"],
                        name="billing_str_event_t_cf3d00_idx",
                    ),
                ],
            },
        ),
    ]
