# Generated by Django 5.2.14 on 2026-06-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('workflow_type', models.CharField(choices=[('report', 'Report')], default='report', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workflows', to='organizations.organization')),
            ],
            options={
                'ordering': ['next_run_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_runs', to='jobs.jobrun')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.scheduledworkflow')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledworkflow',
            index=models.Index(fields=['organization', 'status'], name='jobs_schedu_organiz_e45f41_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledworkflow',
            index=models.Index(fields=['status', 'next_run_at'], name='jobs_schedu_status_13144b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledworkflow',
            index=models.Index(fields=['workflow_type'], name='jobs_schedu_workflo_defd68_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledrun',
            index=models.Index(fields=['workflow', 'created_at'], name='jobs_schedu_workflo_c3450d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledrun',
            index=models.Index(fields=['trigger', 'created_at'], name='jobs_schedu_trigger_67106f_idx'),
        ),
    ]
