# Generated by Django 5.2.14 on 2026-06-03 10:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metric_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('product_scope', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'metric_name', 'period_start', 'period_end'], name='usage_usage_organiz_1fc714_idx'), models.Index(fields=['organization', 'product_scope', 'period_start'], name='usage_usage_organiz_d49c20_idx'), models.Index(fields=['source'], name='usage_usage_source_325c22_idx')],
            },
        ),
    ]
