# Generated by Django 5.2.14 on 2026-06-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization_id', 'provider__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('oauth_token', 'OAuth token'), ('api_key', 'API key'), ('bearer_token', 'Bearer token')], max_length=30)),
                ('encrypted_payload', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='integrations.integrationaccount')),
            ],
            options={
                'ordering': ['integration_account_id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=120)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth 2'), ('api_key', 'API key'), ('none', 'None')], max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('beta', 'Beta'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['slug'], name='integration_slug_68dff9_idx'), models.Index(fields=['category', 'is_active'], name='integration_categor_e75430_idx'), models.Index(fields=['auth_type'], name='integration_auth_ty_2eb0d9_idx')],
            },
        ),
        migrations.AddField(
            model_name='integrationaccount',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='integrations.integrationprovider'),
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rate_limited', 'Rate limited')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_request_id', models.CharField(blank=True, max_length=255)),
                ('rate_limit_reset_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['organization', 'status'], name='integration_organiz_aafa0b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['provider', 'status'], name='integration_provide_6e7137_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['external_account_id'], name='integration_externa_62f79d_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'external_account_id'), name='unique_integration_account_per_external_resource'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['integration_account', 'status'], name='integration_integra_e95912_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['action', 'status'], name='integration_action_ab8eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['external_request_id'], name='integration_externa_46c122_idx'),
        ),
    ]
