# Generated by Django 5.2.14 on 2026-06-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0004_seed_default_ai_task_profiles'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('default_format', models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('docx', 'DOCX')], default='json', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_task_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='ai.aitaskprofile')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('requested_format', models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('docx', 'DOCX')], default='json', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=120)),
                ('related_entity_id', models.CharField(blank=True, max_length=120)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('docx', 'DOCX')], max_length=20)),
                ('storage_backend', models.CharField(default='database', max_length=40)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['report', 'format'], name='reports_rep_report__88541b_idx'), models.Index(fields=['storage_backend'], name='reports_rep_storage_3f35ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['key', 'is_active'], name='reports_rep_key_df38bf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status'], name='reports_rep_organiz_ae5072_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['related_entity_type', 'related_entity_id'], name='reports_rep_related_265023_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
    ]
