// Generated from backend OpenAPI. Run `npm run api:types` after API contract changes.

export const apiPaths = {
  "/api/v1/ai/call-logs/": ["get"],
  "/api/v1/ai/decision-logs/": ["get"],
  "/api/v1/ai/execution-plan/": ["post"],
  "/api/v1/ai/model-policies/": ["get"],
  "/api/v1/ai/prompt-templates/": ["get"],
  "/api/v1/ai/providers/": ["get"],
  "/api/v1/ai/task-profiles/": ["get"],
  "/api/v1/audit/logs/": ["get"],
  "/api/v1/auth/email/verification/resend/": ["post"],
  "/api/v1/auth/email/verify/": ["post"],
  "/api/v1/auth/login/": ["post"],
  "/api/v1/auth/logout/": ["post"],
  "/api/v1/auth/me/": ["get","put","patch"],
  "/api/v1/auth/password/change/": ["post"],
  "/api/v1/auth/password/recover/": ["post"],
  "/api/v1/auth/password/reset/": ["post"],
  "/api/v1/auth/refresh/": ["post"],
  "/api/v1/auth/register/": ["post"],
  "/api/v1/auth/social/google/": ["post"],
  "/api/v1/auth/social/google/status/": ["get"],
  "/api/v1/billing/checkout/": ["post"],
  "/api/v1/billing/customer-portal/": ["post"],
  "/api/v1/billing/entitlements/": ["get"],
  "/api/v1/billing/plans/": ["get"],
  "/api/v1/billing/subscription/": ["get"],
  "/api/v1/billing/webhooks/stripe/": ["post"],
  "/api/v1/integrations/{account_id}/disconnect/": ["post"],
  "/api/v1/integrations/{account_id}/reconnect/": ["post"],
  "/api/v1/integrations/{account_id}/sync-logs/": ["get"],
  "/api/v1/integrations/{provider_slug}/connect/": ["post"],
  "/api/v1/integrations/accounts/": ["get"],
  "/api/v1/integrations/providers/": ["get"],
  "/api/v1/jobs/": ["get"],
  "/api/v1/jobs/schedules/": ["get","post"],
  "/api/v1/jobs/schedules/{workflow_id}/pause/": ["post"],
  "/api/v1/jobs/schedules/{workflow_id}/resume/": ["post"],
  "/api/v1/jobs/schedules/{workflow_id}/run/": ["post"],
  "/api/v1/jobs/schedules/{workflow_id}/runs/": ["get"],
  "/api/v1/notifications/delivery-logs/": ["get"],
  "/api/v1/notifications/preferences/": ["get","post"],
  "/api/v1/organizations/": ["get","post"],
  "/api/v1/organizations/{id}/": ["get","put","patch","delete"],
  "/api/v1/organizations/{id}/invite-member/": ["post"],
  "/api/v1/organizations/{id}/members/": ["get"],
  "/api/v1/privacy/deletion-requests/": ["get","post"],
  "/api/v1/privacy/deletion-requests/{request_id}/execute/": ["post"],
  "/api/v1/privacy/exports/": ["get","post"],
  "/api/v1/products/example-insights/requests/": ["get","post"],
  "/api/v1/reports/": ["get","post"],
  "/api/v1/reports/{id}/": ["get"],
  "/api/v1/reports/{report_id}/artifacts/": ["get"],
  "/api/v1/reports/{report_id}/artifacts/{artifact_id}/download/": ["get"],
  "/api/v1/reports/templates/": ["get"],
  "/api/v1/usage/summary/": ["get"],
} as const;

export type ApiPath = keyof typeof apiPaths;
export type ApiMethodFor<TPath extends ApiPath> = (typeof apiPaths)[TPath][number];
